---
- hosts: all  
  become: yes  

  vars:
     api_token: "p7zvfdc6FxTk3p7syvEx" 
     reg_token: "7q1AsyVKrpJ9Q9s31-Fz"  
     descr: "GCP Runner"

  tasks:
#  - name: "Register runner"
#    community.general.gitlab_runner:
#      api_url: https://gitlab.com/
#      api_token: "{{ api_token }}"
#      registration_token: "{{ reg_token }}"
#      description: GCP Runner
#      state: present
#      active: True
#      tag_list: #i['super']
#      run_untagged: True
#      locked: False
  
  - name: "Delete runner"
    community.general.gitlab_runner:
      api_url: https://gitlab.com/
      api_token: "{{ api_token }}"
      description: "{{ descr }}"
      state: absent
  
#  - name: Delete an owned runner as a non-admin
#    community.general.gitlab_runner:
#      api_url: https://gitlab.example.com/
#      api_token: "{{ access_token }}"
#      description: Docker Machine t1
#      owned: yes
#      state: absent

