#- name: Install ssh key in authorized_keys
#  authorized_key:
#     user: "{{ ssh_user }}"
#     state: "{{ user_status }}"
#     key: "{{ lookup('file', user_pub_key ) }}"
#  become: yes





- name: Install ssh key in authorized_keys  for "{{ user_pub_key }}"
  authorized_key:
     user: "{{ ssh_user }}"
     state: "{{ user_status }}"
     key: "{{ lookup('file', user_pub_key ) }}"
#  ansible_user: root
#  ansible_password: "{{ root_password }}"
