---
#- name: Add the user 'admin' within group of 'admin'
#  ansible.builtin.user:
#    name: admin
#    group: sudo

- name: Create a login user
  user:
     name: "{{ ssh_user }}"
     #password: '???'
     groups:
      - sudo
      #- admin
      #- wheel
     state: present
     shell: /bin/bash       # Defaults to /bin/bash
     system: no             # Defaults to no
     createhome: yes        # Defaults to yes
     #home: /home/fideloper  # Defaults to /home/<username>

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'