---
- hosts: all
  remote_user: root
  #  become: yes
  #  vars_files:
  #    - vault_vars.yml
  vars:
    ansible_user: admin


  tasks:
#  - name: install openvpn
#    apt:
#     name: openvpn
#     state: present
#
#
#  - name: install easyrsa
#    apt:
#     name: easy-rsa
#     state: present





  - name: create openvpn server
    when: inventory_hostname in groups['vpn_servers']
    ansible.builtin.include_role:
      name: robertdebock.openvpn
    vars:
      openvpn_role: "server"

