---
- name: MAZAFACKA
  hosts: all
  remote_user: paul
  become: yes


  tasks:
#    - name: APT update
#      apt:
#          update_cache: true
#          cache_valid_time: 3600
#          force_apt_get: true
    

    - name: create openvpn server
      when: inventory_hostname in groups['vpn_servers']
      ansible.builtin.include_role:
        name: robertdebock.openvpn
      vars:
        openvpn_role: "server"



